<form method="{{method}}" class="uk-form uk-form-horizontal my-form"{{if enctype}} enctype="{{enctype}}"{{end}}>{{BEGIN rows}}
{{BEGIN fieldset-begin}}<fieldset id="fieldset-{{id}}"><legend onclick="toggleFieldset({{id}});"><i class="uk-icon-caret-{{if closed}}right{{else}}down{{end}}"></i> {{title}}</legend><div {{if closed}} class="uk-hidden"{{end}}>{{END}}
{{BEGIN fieldset-end}}</div></fieldset>{{END}}
{{BEGIN hidden}}<input type="hidden" name="{{name}}" value="{{value}}">{{END}}
{{BEGIN text}}<div class="uk-form-row">{{IF title}}<label class="uk-form-label">{{title}}</label>{{END}}<div class="uk-form-controls">{{if icon}}<div class="uk-form-icon"><i class="uk-icon-{{icon}}"></i>{{end}}<input name="{{name}}" type="text" value="{{value}}"{{IF placeholder}} placeholder="{{placeholder}}"{{END}} class="uk-width-*{{IF class}} {{class}}{{END}}">{{if icon}}</div>{{end}}{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN textarea}}<div class="uk-form-row">{{IF title}}<label class="uk-form-label">{{title}}</label>{{END}}<div class="uk-form-controls"><textarea name="{{name}}"{{IF rows}} rows="{{rows}}"{{END}}{{IF placeholder}} placeholder="{{placeholder}}"{{END}} class="uk-width-*{{IF class}} {{class}}{{END}}">{{value}}</textarea>{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN date}}<div class="uk-form-row">{{IF title}}<label class="uk-form-label">{{title}}</label>{{END}}<div class="uk-form-controls"><input name="{{name}}" type="text" value="{{value}}"{{IF placeholder}} placeholder="{{placeholder}}"{{END}} class="uk-width-*{{IF class}} {{class}}{{END}}" data-uk-datepicker>{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN password}}<div class="uk-form-row">{{IF title}}<label class="uk-form-label">{{title}}</label>{{END}}<div class="uk-form-controls"><input name="{{name}}" type="password" value="{{value}}"{{IF placeholder}} placeholder="{{placeholder}}"{{END}} class="uk-width-*{{IF class}} {{class}}{{END}}">{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN select}}<div class="uk-form-row">{{IF title}}<label class="uk-form-label">{{title}}</label>{{END}}<div class="uk-form-controls"><select name="{{name}}" class="uk-width-*{{IF class}} {{class}}{{END}}">{{BEGIN values}}<option value="{{key}}"{{IF selected}} selected="selected"{{END}}>{{value}}</option>{{END}}</select>{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{begin checkbox}}<div class="uk-form-row">{{if title}}<span class="uk-form-label">{{title}}</span>{{end}}<div class="uk-form-controls"><input type="checkbox" name="{{name}}" value="1"{{if checked}} checked="checked"{{end}}>{{if error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{end}}</div></div>{{end}}
{{BEGIN checkboxes}}<div class="uk-form-row">{{IF title}}<span class="uk-form-label">{{title}}</span>{{END}}<div class="uk-form-controls uk-form-controls-text">{{BEGIN values}}<label><input type="checkbox" name="{{name}}[]" value="{{key}}"{{IF checked}} checked="checked"{{END}}> {{title}}</label><br>{{END}}{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN checkboxes-col-2}}<div class="uk-form-row">{{IF title}}<span class="uk-form-label">{{title}}</span>{{END}}<div class="uk-form-controls uk-form-controls-text uk-flex uk-flex-wrap uk-flex-wrap-space-around">{{BEGIN values}}<div class="uk-width-1-2"><label><input type="checkbox" name="{{name}}[]" value="{{key}}"{{IF checked}} checked="checked"{{END}}> {{title}}</label></div>{{END}}{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}</div></div>{{END}}
{{BEGIN checkboxes-col-3}}<div class="uk-form-row">{{IF title}}<span class="uk-form-label">{{title}}</span>{{END}}<div class="uk-form-controls uk-form-controls-text uk-flex uk-flex-wrap uk-flex-wrap-space-around">{{BEGIN values}}<div class="uk-width-1-3"><label><input type="checkbox" name="{{name}}[]" value="{{key}}"{{IF checked}} checked="checked"{{END}}> {{title}}</label></div>{{END}}{{IF error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{END}}{{IF helper}}<p class="uk-form-help-block uk-text-small">{{helper}}</p>{{END}}</div></div>{{END}}
{{begin file}}<div class="uk-form-row">{{if title}}<label class="uk-form-label">{{title}}</label>{{end}}<div class="uk-form-controls"><input{{if id}} id="{{id}}"{{end}} name="{{name}}" type="file"{{if placeholder}} placeholder="{{placeholder}}"{{end}} class="uk-width-*{{if class}} {{class}}{{end}}">{{if error}}<p class="uk-form-help-block uk-text-danger uk-text-small">{{error}}</p>{{end}}</div></div>{{end}}
{{BEGIN submit}}<div class="uk-form-row"><div class="uk-form-controls"><button name="{{name}}" type="submit" class="uk-button uk-button-small uk-button-primary">{{title}}</button></div></div>{{END}}
{{END}}</form>